### ISSUE TITLE
comparison to 0bin?

### ISSUE THREAD

**Issue by elijh** [Upload/Up1#10]
Great project. Are you aware of the similar 0bin? https://github.com/sametmax/0bin

It also uses SJCL, but with python backend. It would be useful to have a comparison of the approaches and capabilities of these similar projects.

**Comment by k3d3** [comment]
There are several differences between the applications, however this isn't really the place to discuss it. We want to reserve the issue tracker for bugs and features.

That being said, I wrote a small comparison between Up1 and img.bi on reddit if you're interested, at http://www.reddit.com/r/netsec/comments/3az3jp/we_made_up1_an_open_source_clientside_encrypted/cshk1dc?context=1 .

I'm going to go ahead and close this issue.
