### ISSUE TITLE
Image jumps to smallest size if dragged a certain way

### ISSUE THREAD

**Issue by k3d3** [Upload/Up1#2]
In order to reproduce this bug, go to an image, zoom it in as far as possible by dragging, then move to the bottom-right corner of the image and try to drag it back.

It appears to instantly jump to the minimum size, and this shouldn't happen.

**Comment by andre-d** [comment]
I'll pull an average in to try to get it to move less when moving a large
amount at an extreme.

**Comment by andre-d** [comment]
Should be fixed in e7cbc9fcabcc1f54c30f5625ccf05d1505a53b02
