### ISSUE TITLE
Different View-Path than "/#"

### ISSUE THREAD

**Issue by Z3roCoder** [Upload/Up1#28]
Currently I am wanting to make the upload-functionality usable ONLY by users that can authentificate themselves (currently via htpasswd) and do that with NGinx location in terms of 

```
 location / {
        proxy_pass serverURL;
        auth_basic "Upload-Site";
        auth_basic_user_file /var/www/dl/pass.txt;
    }
  }
```
But now the problem is that "#" is such a special symbol that the server never knows anything about when a image is viewed and thus I can not say "When you access an image to look at it do not ask for credentials"

It would be awesome if the URL could be instead of "url/#somestring" something like "url/v/sometring" or "url/view/somestring"

Is something like that possible?

**Comment by andre-d** [comment]
The fragment is used as it is not sent to the server.  If you send the seed
to the sever you compromise the entire system as your sever can now decrypt
every upload.

You could switch it instead to

/view/#seed instead and have the sever return the same html contents for
/view/

**Comment by Z3roCoder** [comment]
@andre-d How would I go about and do that?

**Comment by ultramancool** [comment]
We'll be looking into adding auth functionality in the future, it should be possible if you apply auth only to the upload "/up" URL. Try that if you want @Z3roCoder . Closing this for now as the basic idea here would fundamentally break the purpose of up1.
