### ISSUE TITLE
Show "Share"-URL + Possbility for Short-URLs (e.g with YOURLS)

### ISSUE THREAD

**Issue by Z3roCoder** [Upload/Up1#30]
That would be very useful that a paste, image or anything else uploaded would not only have the name displayed on the top right, but also the link, as well as the direct link it can be shared and viewed from!

Also a possible implementation for Short-URLs would be awesome to have, as an example from a self-hosted YOURLS-Server: http://yourls.org/

**Comment by ultramancool** [comment]
Short URLS are not possible as the seed (the part after the #) is a cryptographic key and we don't want to bring that under a good level of cryptographic strength. If you want to send your seeds to a URL shortener, you can do so, but we strongly recommend against it as it reveals your seeds to an unnecessary 3rd party.
