### ISSUE TITLE
Disable public uploads

### ISSUE THREAD

**Issue by ClayF** [Upload/Up1#40]
I'm looking to use this as a private tool for filesharing via ShareX, but it seems to me that anyone with the URL can upload files. I'm looking to only allow downloads.

**Comment by k3d3** [comment]
There's an api_key setting in config.js - just set that to nothing and it'll prevent uploads on the web side. You'll still need to set the API key in ShareX though.

**Comment by ClayF** [comment]
Ah. I see it now. I was confused because it still allowed me to download the files. I did not realize it was a cached copy.
