### ISSUE TITLE
Image rotation not working

### ISSUE THREAD

**Issue by tehmaze** [Upload/Up1#49]
##### Problem:
Images with EXIF orientation set are not properly rotated on display.

##### Steps to reproduce:
Upload a JPEG with Orientation field set to 90 degrees CW/CCW in the EXIF tags.

##### Expected:
Expected the image to show as portrait, but in stead the image is in landscape mode.

Preview is not working:
![Preview](https://www.dropbox.com/s/7ht38w0yk9cxev2/Screenshot%202016-02-08%2012.21.57.png?raw=1)

Show in browser works as expected:
![Show in browser](https://www.dropbox.com/s/m7u6m12m1mt8pbf/Screenshot%202016-02-08%2012.22.05.png?raw=1)

**Comment by tehmaze** [comment]
For completeness:

    % exiftool IMG_7783.jpg | grep Orientation
    Orientation                     : Rotate 90 CW

**Comment by andre-d** [comment]
Submit a bug with your browser vendor.  The only way this is resolved by
other image hosts is reading the exif data and manually rotating it
themselves on the server on upload which is not a case a client side
processed host can handle.

**Comment by anarcat** [comment]
There's a [image-rotation](https://developer.mozilla.org/en-US/docs/Web/CSS/image-orientation) CSS tag you *must* use to have this work, and it only works in Firefox (26+) right now. So while we can open bug reports with "downstream" web browsers all we want, there is still something to be done in up1 to have this work at all. I think what you need is `img { image-rotation: from-image }`.
