### ISSUE TITLE
Content Id and the Key

### ISSUE THREAD

**Issue by xeverse** [Upload/Up1#50]
What part of the uri is content identifier and which is the key?
http://uploadereqo2cmg7.onion/#f3qY8nEX81J1tmMKFzpeyQ

**Comment by ultramancool** [comment]
The part after the # is both. Rather, SHA512 is used on that random string
to produce a 128 bit IV, 256 bit key and 128 bit random identifier.

**Comment by xeverse** [comment]
Ahh ok, thanks. So only 128 bit identifier gets sent to the server side by the js. Correct?

**Comment by ultramancool** [comment]
yes, that's correct. Key and IV are kept entirely on the client side and
never sent to the server.

**Comment by xeverse** [comment]
I miss super cool https://github.com/imgbi. Been down for quite some time.
So i  just want to be sure that both apps are equally secure.
The implementation looks similar a least.
