### ISSUE TITLE
Replace highlight.js with prism.js?

### ISSUE THREAD

**Issue by k0nsl** [Upload/Up1#51]
Would there be any interest in replacing `highlight.js` with `prism.js`<sup>1</sup>?

Refs.
1. [https://github.com/PrismJS/prism](https://github.com/PrismJS/prism)

**PS:** seems like I haven't followed this project for sometime now, as it was still written in Golang when I used it 😂

**Comment by andre-d** [comment]
The reason we use highlight is the language auto detection.  It we can
replace that portion I would look into replacing with one of many different
highlight engines.

**Comment by k3d3** [comment]
> PS: seems like I haven't followed this project for sometime now, as it was still written in Golang when I used it 😂

It actually still is written in Golang, however we've added a second Node server for the time being. Both are currently maintained and we don't have any plans for deprecation at the moment.

**Comment by andre-d** [comment]
The advantage of the Go server is that it is dependency free beyond Go itself

**Comment by k0nsl** [comment]
@andre-d:
Yes, that's the issue I stumbled upon when I tried to replace it myself. I couldn't be bothered with it and reverted back to the latest release of `highlight.js` :)

@k3d3:
Thanks for the clarification.
