### ISSUE TITLE
only paste, without upload?

### ISSUE THREAD

**Issue by alanford2015** [Upload/Up1#52]
Hi,
this project is goo but I have one question: 
it is possible to install at my VPS/debian only paste, without upload of files, from this up1 git?
how can I exclude upload installation?

regards,
alan

**Comment by andre-d** [comment]
We do not currently have a configurable parameter for the frontend and it
is not possible for it to detect binary files on the server as the sever is
accepting encrypted blobs but for now I suggest lowering the max upload
size.

**Comment by k3d3** [comment]
I'm going to close this issue, as it has been clarified.
