### ISSUE TITLE
Upload by URL

### ISSUE THREAD

**Issue by ipatjolvur** [Upload/Up1#56]
Enhancement request:
Allow uploading images (or any filetypes) by their URL, not only from the user's machine.

Other (open source) hosts listed in ShareX offer that option, but Up1 is a more security-conscious project than most of them, so I would prefer it to have a similar option.

**Comment by andre-d** [comment]
Sites which do this like imgur are doing so by downloading the image on the server first.  The JS client can technically download images from other servers but only ones CORS enabled so this is not worth the effort for the few servers which might actually let the user download the image cross origin.
