### ISSUE TITLE
roundcube extension

### ISSUE THREAD

**Issue by ran290** [Upload/Up1#9]
Hi, I tried to [reply to k3d3](https://news.ycombinator.com/item?id=9773741) on HN but it appears the comment was lost..

My reply was as follows:
> An extension for roundcube (https://roundcube.net/) to suppliment or replace the email attach function would be pretty cool

**Comment by andre-d** [comment]
There are no plans for first-party support for the requested application at this time.  We are choosing to focus on browser add-ons with an integrated copy of the client for enhanced security.  If there are ways to better integrate with other sites (like roundcube), please add an issue with the browser addon once they get released.
